DROP TABLE IF EXISTS DEVELOPERS;
CREATE TABLE DEVELOPERS(ID INT PRIMARY KEY AUTO_INCREMENT,
   NAME VARCHAR(255));

INSERT INTO DEVELOPERS(NAME) VALUES('STEVEN');
INSERT INTO DEVELOPERS(NAME) VALUES('MUSA');
INSERT INTO DEVELOPERS(NAME) VALUES('`WOLE');

